### ISSUE TITLE
Existing Open API specification (for scoring API) doesn't correspond latest changes

### ISSUE THREAD

**Issue by tivaliy** [intento/intento-api#48]
Hi,

I'm trying to generate client based on Open API specification you've defined here - https://github.com/intento/intento-api/blob/master/score.openapi.json 

The problem that I have the following error response:

```{"error": {"code": 413, "message": "Parameter \\"scores\\" is required when using evaluation"}}```

It seems to me that this one (https://github.com/intento/intento-api/blob/master/score.openapi.json#L333-L365) doesn't correspond to what we have in `score.md`:

```
curl  -XPOST -H 'apikey: YOUR_API_KEY' 'https://api.inten.to/evaluate/score'  -d '{
    "data": {
        "items": [
            "A sample text",
            "Some other text"
        ],
        "reference": [
            "Not a sample text",
            "Some other context"
        ],
        "source": [
            "Un texto de muestra",
            "Algún otro texto"
        ],
        "lang": "en"
    },
    "scores": [
        {
            "name": "comet",
            "ignore_errors": true
        }
    ],
    "itemize": false,
    "async": true
}'
```

Thoughts?

**Comment by phen0menon** [comment]
Thanks for the issue @tivaliy. Will be fixed asap

**Comment by phen0menon** [comment]
Fixed in https://github.com/intento/intento-api/pull/49
